---

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: apt-get update 
      raw: apt-get update

    - name: apt-get upgrade
      raw: apt-get upgrade -y

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: install nginx fcgi
      raw: apt-get install nginx-full python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools -y
    - name: install python-env
      raw: sudo apt install python3-venv -y
- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: mkdir
      raw:  mkdir ~/myproject

    - name: 
      raw: cd ~/myproject

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: venv
      raw: python3.6 -m venv myprojectenv

    - name: venv2
      raw: source myprojectenv/bin/activate


