---

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: apt-get update 
      raw: apt-get update -y

    - name: apt-get upgrade
      raw: apt-get upgrade -y

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: install nginx and python
      raw: apt-get install nginx-full python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools -y
    - name: install python-env
      raw: sudo apt install python3-venv -y
- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

   - name: mkdir
     raw:  mkdir ~/myproject

   - name: cd 
     raw: cd ~/myproject

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

    - name: venv
      raw: python3.6 -m venv myprojectenv

    - name: venv2
      raw: source myprojectenv/bin/activate

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:
     - name: apt-get install pip -y
       raw: apt-get install python3-pip -y
 
     - name: install wheel
       raw: pip3 install wheel


- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:
      
      - name: install flask
        raw: pip install uwsgi flask

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:
      - name: create symlink
        raw: ln -s /etc/nginx/sites-available/myproject /etc/nginx/sites-enabled


- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

      - name: install postgre
        raw: apt-get install postgresql -y

- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

      - name: create username postgre
        raw:  sudo -u postgres createuser testuser123

      - name: create db
        raw: sudo -u postgres createdb testdb1 


- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

          - name: start project
            raw: sudo systemctl start myproject

          - name: enable project
            raw: sudo systemctl enable myproject  
- name: playbook
  hosts: myhosts
  gather_facts: false

  tasks:

      - name: restart nginx
        raw:  systemctl restart nginx

